### ISSUE TITLE
mapd crash in Route.py

### ISSUE THREAD

**Issue by eFiniLan** [move-fast/openpilot#11]
Please see image attached and let me know if you need more information :)

This happened in dp integration but I believe this is the stock code (@rav4kumar can you point out which mapd version we have in the latest dp pre branch?) 

![Screenshot from 2021-10-19 16-28-54](https://user-images.githubusercontent.com/16603033/137872729-c2123345-1f2f-400d-b95f-a90f9bd58d5c.png)

**Comment by rav4kumar** [comment]
https://github.com/move-fast/openpilot/tree/release_0.8.9

**Comment by alfhern** [comment]
@eFiniLan : Can you send me the link to the exact codebase you are using. I have fixed this issue before, but I need to confirm if the fix is not in your code, otherwise is something else. Thanks.

**Comment by eFiniLan** [comment]
Hi @alfhern,

thanks for the reply, here is the link: https://github.com/eFiniLan/dp-devel/tree/0.8.9-pre (I think you have access to it )

my short drive today seems fine, it would be great if you can take a quick look, in the mean time I will keep testing it :)

cheers!

**Comment by alfhern** [comment]
Thanks @eFiniLan : 
The code seems up to date with all our current code base, including fix for when I saw this  issue.
If you can point me in a map where this happened and the direction of travel, I could probably recreate the scenario in our test notebook and see what the issue is.
Cheers.

**Comment by eFiniLan** [comment]
Hi @alfhern ,
Thanks for checking the code! I've encountered the same error again yesterday afternoon.
Here is my route (starting from The Park Way):

<img width="1039" alt="Screen Shot 2021-10-25 at 2 44 26 PM" src="https://user-images.githubusercontent.com/16603033/138635881-8c261075-f740-4c07-882c-c95e2cbb82e6.png">

the mapd showed road name "Hawthorn Circuit" before it crashed, so I guess it's crashed near the roundabout

Here is the link to OSM:
https://www.openstreetmap.org/#map=18/-27.62703/153.06133

cheers!

**Comment by alfhern** [comment]
HI @eFiniLan:
Thank for the info. Unfortunately (for the research) I can recreate the route without having any issue.

Are you sure you are running the latest and greatest `0.8.9-pre`?  The issue you are describing was exactly what was happening around two weeks ago on some roundabout scenarios after I made some improvements to the routing logic and introduced a bug in the process.
Two weeks ago, this exact route would have failed as you described and with the same way ids. i.e. `-2`.

Could you please confirm you are in the latest ref.. or send me the complete git ref of your HEAD so I can make sure I am checking the right piece of code..

Thanks.

**Comment by eFiniLan** [comment]
Hey @alfhern,

Yes I'm on the latest commit and it did crash again, I will give it a try again tomorrow and dump the route in gpx format see if that helps :)

**Comment by alfhern** [comment]
This is very strange. Basically this crash is happening when creating a route, and creating a route just takes a GPS location and a bearing. I can replicate exactly that locally, and as said, with latest codebase it works fine.  I tried a bunch of different locations around the roundabout from your report, all working fine. I tried it before my fix and the issue popped up, exactly as you reported it.
So that is why is quite confusing to me.. If you can give me coordinates of places it fail I can keep trying to find a braking scenario. Thanks.

**Comment by eFiniLan** [comment]
Hi @alfhern,

Sorry for the delay, please see the attached gpx log, the error is still the same:
```python
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/manager/process.py", line 36, in launcher
    mod.main()
  File "/data/openpilot/selfdrive/mapd/mapd.py", line 256, in main
    mapd_thread(sm, pm)
  File "/data/openpilot/selfdrive/mapd/mapd.py", line 250, in mapd_thread
    mapd.update_route()
  File "/data/openpilot/selfdrive/mapd/mapd.py", line 176, in update_route
    update_proc()
  File "/data/openpilot/selfdrive/mapd/mapd.py", line 169, in update_proc
    self.route = self.way_collection.get_route(self.location_rad, self.bearing_rad, self.location_stdev)
  File "/data/openpilot/selfdrive/mapd/lib/WayCollection.py", line 85, in get_route
    return Route(current, self.wr_index, self.id, self.query_center)
  File "/data/openpilot/selfdrive/mapd/lib/Route.py", line 86, in __init__
    last_wr_idx = way_relations.index(last_wr)
ValueError: (id: -1, between None and None, DIRECTION.BACKWARD, active: False) is not in list
```


[3935902.zip](https://github.com/move-fast/openpilot/files/7577591/3935902.zip)

**Comment by alfhern** [comment]
Thanks @eFiniLan : Are you experiencing it also in `0.8.10-pre`??

**Comment by rav4kumar** [comment]
> Thanks @eFiniLan : Are you experiencing it also in `0.8.10-pre`??

Yes, it is still present on current release.

**Comment by alfhern** [comment]
Ok @eFiniLan : I think I managed to reproduce the issue. 
Is it happening after the roundabout in the south direction? Like the arrow in the image below? Tx

<img width="1035" alt="Screenshot 2021-11-23 at 08 42 51" src="https://user-images.githubusercontent.com/3198019/142986848-f95bf0c6-7f1b-457e-83a3-c285ce4a9f08.png">

**Comment by alfhern** [comment]
@eFiniLan , @rav4kumar :
I have found the issue and corrected it on our release branch.
Please see this commit for details:
https://github.com/move-fast/openpilot/commit/add08479ae7391f290f97b917cc27393be0c3e38

**Comment by alfhern** [comment]
@eFiniLan : Please verify and reopen if still existing.

**Comment by eFiniLan** [comment]
> @eFiniLan : Please verify and reopen if still existing.

Hi @alfhern,

Thanks for the fix, it's been working really well. :)
